### PR TITLE
Update upkie version

### PR DESCRIPTION
**Pull request by ubgk**

### CODE REVIEW

**Comment by ubgk** [comment]
```
$ ./tools/bazel run //pink_balancer -- -c bullet
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Starting local Bazel server and connecting to it...
INFO: Analyzed target //pink_balancer:pink_balancer (56 packages loaded, 1507 targets configured).
INFO: Found 1 target...
Target //pink_balancer:pink_balancer up-to-date:
  bazel-bin/pink_balancer/pink_balancer
INFO: Elapsed time: 14.460s, Critical Path: 0.14s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/pink_balancer/pink_balancer -c bullet
[2024-01-18 15:11:25,195] [info] Loading configuration 'common.gin' (main.py:75)
[2024-01-18 15:11:25,199] [info] Loading configuration 'bullet.gin' (main.py:75)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_bora/9fe7a4df9875153d3410245d618871e5/execroot/pink_balancer/bazel-out/darwin-opt/bin/pink_balancer/pink_balancer.runfiles/pink_balancer/pink_balancer/main.py", line 99, in <module>
    spine = SpineInterface()
  File "/private/var/tmp/_bazel_bora/9fe7a4df9875153d3410245d618871e5/execroot/pink_balancer/bazel-out/darwin-opt/bin/pink_balancer/pink_balancer.runfiles/vulp/vulp/spine/spine_interface.py", line 90, in __init__
    self.__perf_checks()
  File "/private/var/tmp/_bazel_bora/9fe7a4df9875153d3410245d618871e5/execroot/pink_balancer/bazel-out/darwin-opt/bin/pink_balancer/pink_balancer.runfiles/vulp/vulp/spine/spine_interface.py", line 97, in __perf_checks
    raise PerformanceIssue("msgpack is running in pure Python")
vulp.spine.exceptions.PerformanceIssue: msgpack is running in pure Python
```

This PR doesn't run due to msgpack using the wrong backend.

**Comment by stephane-caron** [comment]
Oh I see, that's a version installed by Bazel's ``rules_python`` in https://github.com/upkie/vulp/issues/77

That thing has been yielding too much complexity for its benefits. Let's blast it in favor of Conda/PyPI alternatives :fire:

**Comment by stephane-caron** [comment]
@ubgk you can try the update in https://github.com/stephane-caron/pink_balancer/pull/2. CI pipelines are still running, but it blasts all Bazel `rules_python` dependencies, therefore imported packages will all be from your current environment (that part is simplified :wink:).

**Comment by stephane-caron** [comment]
CI passed and it worked when I tested on my machine, so I've merged the update to the main branch. Does it work for you after that?

**Comment by ubgk** [comment]
Yes, it seems to work! Cheers.

**Comment by stephane-caron** [comment]
OK, closing this PR then :+1: Feel free to reopen if future updates are required.

**Pull request closed without merging**
